Change create-cert to create a certificate authority as well
A certificate authority may be easier to add to browsers.

diff --git a/create-cert b/create-cert
--- a/create-cert
+++ b/create-cert
@@ -2,25 +2,13 @@
 
 set -e
 
-keyfile=backend/otsv
+basename=backend/otsv
+ca_key=$basename-ca-key.pem
+ca_cert=$basename-ca-cert.pem
+key=$basename-key.pem
+cert=$basename-cert.pem
 
-die() {
-    echo "$*"
-    exit 1
-}
-
-! [ -e "$keyfile-key.pem" ] || \
-    die "File $keyfile-key.pem exists"
-! [ -e "$keyfile-cert.pem" ] || \
-    die "File $keyfile-cert.pem exists"
-
-config=$(cat <<-EOF
-    [req]
-    distinguished_name = distinguished_name
-    x509_extensions = req_exts
-    utf8 = yes
-    prompt = no
-
+distinguished_name=$(cat <<-EOF
     [distinguished_name]
     countryName = AT
     stateOrProvinceName = ST
@@ -28,10 +16,36 @@ config=$(cat <<-EOF
     organizationName = Andreas Grünbacher
     commonName = TrialInfo
     emailAddress = auswertung@otsv.at
+EOF
+)
+
+ca_config=$(cat <<-EOF
+    [req]
+    distinguished_name = distinguished_name
+    x509_extensions = req_exts
+    utf8 = yes
+    prompt = no
+
+    [req_exts]
+    basicConstraints = CA:TRUE
+    keyUsage = critical, keyCertSign, cRLSign
+
+    $(echo "$distinguished_name")
+EOF
+)
+
+config=$(cat <<-EOF
+    [req]
+    distinguished_name = distinguished_name
+    req_extensions = req_exts
+    utf8 = yes
+    prompt = no
+
+    $(echo "$distinguished_name")
 
     [req_exts]
     keyUsage = digitalSignature, keyEncipherment
-    extendedKeyUsage = serverAuth,clientAuth
+    extendedKeyUsage = serverAuth
     subjectAltName = @alternate_names
 
     [alternate_names]
@@ -43,17 +57,55 @@ config=$(cat <<-EOF
 EOF
 )
 
-openssl req \
-    -config <(echo "$config") \
-    -x509 \
-    -nodes \
-    -newkey rsa:4096 \
-    -sha256 \
-    -days 36500 \
-    -keyout $keyfile-key.pem \
-    -out $keyfile-cert.pem
+die() {
+    echo "$*"
+    exit 1
+}
 
-openssl x509 \
-    -nameopt utf8 \
-    -in $keyfile-cert.pem \
-    -text
+if [ -e "$ca_key" -o -e "$ca_cert" ]; then
+    [ -e "$ca_key" ] || die "File $ca_key is missing"
+    [ -e "$ca_cert" ] || die "File $ca_cert is missing"
+    echo "Files $ca_key and $ca_cert exist"
+else
+    openssl req \
+	-config <(echo "$ca_config") \
+	-x509 \
+	-nodes \
+	-newkey rsa:4096 \
+	-sha256 \
+	-days 36500 \
+	-keyout "$ca_key" \
+	-out "$ca_cert"
+fi
+
+if [ -e "$key" -o -e "$cert" ]; then
+    [ -e "$key" ] || die "File $key is missing"
+    [ -e "$cert" ] || die "File $cert is missing"
+    echo "Files $key and $cert exist"
+else
+    csr=$(mktemp)
+    cleanup() {
+	rm -f "$csr"
+    }
+    trap cleanup EXIT
+
+    openssl req \
+	-config <(echo "$config") \
+	-nodes \
+	-newkey rsa:4096 \
+	-sha256 \
+	-days 36500 \
+	-keyout "$key" \
+	-out "$csr"
+
+    openssl x509 \
+	-req \
+	-days 36500 \
+	-in "$csr" \
+	-extensions req_exts \
+	-extfile <(echo "$config") \
+	-CA "$ca_cert" \
+	-CAkey "$ca_key" \
+	-set_serial 1 \
+	-out "$cert"
+fi
